os: linux
dist: bionic
language: node_js
node_js:
    - "node"
    - "14"
    - "13"
    - "12"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
    yarn: true
script:
    - yarn test
    - yarn coveralls
